<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KurikulumSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // Semester 1
            [
                'semester' => 1,
                'kode_mk' => 'IF101',
                'nama_mk' => 'Algoritma dan Pemrograman 1',
                'nama_mk_eng' => 'Algorithms and Programming 1',
                'nama_singkat_mk' => 'Algo Pemrog 1',
                'sks' => 3,
                'deskripsi_mk' => 'Dasar-dasar algoritma dan pemrograman berorientasi objek.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 1,
                'kode_mk' => 'IF102',
                'nama_mk' => 'Matematika Diskrit',
                'nama_mk_eng' => 'Discrete Mathematics',
                'nama_singkat_mk' => 'Mat Diskrit',
                'sks' => 3,
                'deskripsi_mk' => 'Konsep dasar matematika diskrit untuk ilmu komputer.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 1,
                'kode_mk' => 'IF103',
                'nama_mk' => 'Bahasa Inggris Teknik',
                'nama_mk_eng' => 'Technical English',
                'nama_singkat_mk' => 'B Inggris',
                'sks' => 2,
                'deskripsi_mk' => 'Bahasa Inggris untuk kebutuhan teknik informatika.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 1,
                'kode_mk' => 'IF104',
                'nama_mk' => 'Pengantar Informatika',
                'nama_mk_eng' => 'Introduction to Informatics',
                'nama_singkat_mk' => 'Peng Informatika',
                'sks' => 3,
                'deskripsi_mk' => 'Pengantar konsep dasar informatika dan komputer.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],

            // Semester 2
            [
                'semester' => 2,
                'kode_mk' => 'IF201',
                'nama_mk' => 'Algoritma dan Pemrograman 2',
                'nama_mk_eng' => 'Algorithms and Programming 2',
                'nama_singkat_mk' => 'Algo Pemrog 2',
                'sks' => 3,
                'deskripsi_mk' => 'Lanjutan algoritma dan pemrograman dengan struktur data.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 2,
                'kode_mk' => 'IF202',
                'nama_mk' => 'Basis Data',
                'nama_mk_eng' => 'Database',
                'nama_singkat_mk' => 'Basis Data',
                'sks' => 3,
                'deskripsi_mk' => 'Dasar-dasar sistem basis data relasional.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 2,
                'kode_mk' => 'IF203',
                'nama_mk' => 'Sistem Operasi',
                'nama_mk_eng' => 'Operating Systems',
                'nama_singkat_mk' => 'Sisop',
                'sks' => 3,
                'deskripsi_mk' => 'Konsep dasar sistem operasi dan manajemen proses.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 2,
                'kode_mk' => 'IF204',
                'nama_mk' => 'Pemrograman Web 1',
                'nama_mk_eng' => 'Web Programming 1',
                'nama_singkat_mk' => 'Web Prog 1',
                'sks' => 3,
                'deskripsi_mk' => 'Dasar pemrograman web dengan HTML, CSS, JS.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],

            // Semester 3
            [
                'semester' => 3,
                'kode_mk' => 'IF301',
                'nama_mk' => 'Struktur Data dan Algoritma',
                'nama_mk_eng' => 'Data Structures and Algorithms',
                'nama_singkat_mk' => 'Struk Data',
                'sks' => 3,
                'deskripsi_mk' => 'Implementasi struktur data lanjutan.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 3,
                'kode_mk' => 'IF302',
                'nama_mk' => 'Rekayasa Perangkat Lunak',
                'nama_mk_eng' => 'Software Engineering',
                'nama_singkat_mk' => 'Rekayasa PL',
                'sks' => 3,
                'deskripsi_mk' => 'Proses pengembangan perangkat lunak.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 3,
                'kode_mk' => 'IF303',
                'nama_mk' => 'Jaringan Komputer',
                'nama_mk_eng' => 'Computer Networks',
                'nama_singkat_mk' => 'Jarkom',
                'sks' => 3,
                'deskripsi_mk' => 'Dasar jaringan komputer dan protokol.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 3,
                'kode_mk' => 'IF304',
                'nama_mk' => 'Pemrograman Berorientasi Objek',
                'nama_mk_eng' => 'Object-Oriented Programming',
                'nama_singkat_mk' => 'PBO',
                'sks' => 3,
                'deskripsi_mk' => 'Konsep OOP dalam pemrograman.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],

            // Semester 4
            [
                'semester' => 4,
                'kode_mk' => 'IF401',
                'nama_mk' => 'Desain Basis Data',
                'nama_mk_eng' => 'Database Design',
                'nama_singkat_mk' => 'Desain BD',
                'sks' => 3,
                'deskripsi_mk' => 'Desain dan normalisasi basis data.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 4,
                'kode_mk' => 'IF402',
                'nama_mk' => 'Sistem Informasi',
                'nama_mk_eng' => 'Information Systems',
                'nama_singkat_mk' => 'Sisinfo',
                'sks' => 3,
                'deskripsi_mk' => 'Pengembangan sistem informasi.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 4,
                'kode_mk' => 'IF403',
                'nama_mk' => 'Keamanan Jaringan',
                'nama_mk_eng' => 'Network Security',
                'nama_singkat_mk' => 'Keamanan Jarkom',
                'sks' => 3,
                'deskripsi_mk' => 'Konsep keamanan di jaringan komputer.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 4,
                'kode_mk' => 'IF404',
                'nama_mk' => 'Pemrograman Mobile',
                'nama_mk_eng' => 'Mobile Programming',
                'nama_singkat_mk' => 'Mobile Prog',
                'sks' => 3,
                'deskripsi_mk' => 'Pengembangan aplikasi mobile.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],

            // Semester 5
            [
                'semester' => 5,
                'kode_mk' => 'IF501',
                'nama_mk' => 'Intelijen Buatan',
                'nama_mk_eng' => 'Artificial Intelligence',
                'nama_singkat_mk' => 'AI',
                'sks' => 3,
                'deskripsi_mk' => 'Dasar-dasar kecerdasan buatan.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 5,
                'kode_mk' => 'IF502',
                'nama_mk' => 'Data Mining',
                'nama_mk_eng' => 'Data Mining',
                'nama_singkat_mk' => 'Data Mining',
                'sks' => 3,
                'deskripsi_mk' => 'Teknik penambangan data.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 5,
                'kode_mk' => 'IF503',
                'nama_mk' => 'Pengembangan Web Lanjutan',
                'nama_mk_eng' => 'Advanced Web Development',
                'nama_singkat_mk' => 'Web Lanjutan',
                'sks' => 3,
                'deskripsi_mk' => 'Teknologi web modern.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 5,
                'kode_mk' => 'IF504',
                'nama_mk' => 'Manajemen Proyek TI',
                'nama_mk_eng' => 'IT Project Management',
                'nama_singkat_mk' => 'Manpro TI',
                'sks' => 3,
                'deskripsi_mk' => 'Manajemen proyek di bidang TI.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],

            // Semester 6
            [
                'semester' => 6,
                'kode_mk' => 'IF601',
                'nama_mk' => 'Machine Learning',
                'nama_mk_eng' => 'Machine Learning',
                'nama_singkat_mk' => 'ML',
                'sks' => 3,
                'deskripsi_mk' => 'Dasar machine learning dan aplikasi.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 6,
                'kode_mk' => 'IF602',
                'nama_mk' => 'Big Data',
                'nama_mk_eng' => 'Big Data',
                'nama_singkat_mk' => 'Big Data',
                'sks' => 3,
                'deskripsi_mk' => 'Pengelolaan dan analisis big data.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 6,
                'kode_mk' => 'IF603',
                'nama_mk' => 'Cloud Computing',
                'nama_mk_eng' => 'Cloud Computing',
                'nama_singkat_mk' => 'Cloud',
                'sks' => 3,
                'deskripsi_mk' => 'Konsep komputasi awan.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
            [
                'semester' => 6,
                'kode_mk' => 'IF604',
                'nama_mk' => 'Etika Profesi TI',
                'nama_mk_eng' => 'IT Professional Ethics',
                'nama_singkat_mk' => 'Etika TI',
                'sks' => 2,
                'deskripsi_mk' => 'Etika dan profesionalisme di TI.',
                'created_by' => 'system',
                'updated_by' => null,
                'active' => 1,
            ],
        ];

        foreach ($data as $item) {
            \App\Models\Kurikulum::create($item);
        }
    }
}
